name: Push to main

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: 'Setup Node'
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: 'Install Dependencies'
        run: npm ci

      - name: 'Build Action'
        run: npm run build

      - name: 'Zip Library'
        run: zip -r batcher.zip dist/

      - name: 'Release'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
