name: 'Pull Request'

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  verify:
    if: ${{ !startsWith(github.head_ref, 'dependabot/')  }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3.6.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: 'Install NPM Packages'
        run: npm ci

      - name: 'Run Commitlint'
        if: ${{ !contains(github.head_ref, 'batched-dependabot-updates') }}
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: 'Run Lint'
        run: npm run lint

      - name: 'Run Unit Tests'
        run: npm run test

      - name: 'Create Build Artifact'
        run: npm run build

      - name: 'Upload Build Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist
          if-no-files-found: error
